name: Performance Benchmark

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
      env:
        NODE_OPTIONS: --experimental-vm-modules

    - name: Run benchmarks
      run: |
        # Fix TypeScript execution by using ts-node with proper flags for ESM
        NODE_OPTIONS="--experimental-vm-modules" npx ts-node-esm -P tsconfig.json benchmarks/benchmarks.ts || \
        NODE_OPTIONS="--experimental-vm-modules" npx tsx benchmarks/benchmarks.ts || \
        NODE_OPTIONS="--experimental-vm-modules" node -r ts-node/register benchmarks/benchmarks.ts

    - name: Store benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results/
