name: Performance Benchmark

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50  # Get enough history for benchmark comparisons

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      env:
        NEXUREJS_CI_MODE: 0  # Need native modules for benchmarks

    - name: Build
      run: npm run build:ts
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Build native modules
      run: node scripts/build.js --force
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Run benchmarks
      run: node --max-old-space-size=4096 --loader ts-node/esm benchmarks/benchmarks.ts
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
        NODE_ENV: production

    - name: Store benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results/
        retention-days: 30

    - name: Compare benchmark results
      run: node scripts/compare-benchmarks.js --threshold=7
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
      continue-on-error: true
