name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci
      env:
        NEXUREJS_CI_MODE: 1

    - name: Build TypeScript
      run: npm run build:ts
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Build native modules
      run: node scripts/build.js --force
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Package native modules
      run: node scripts/build.js --pack-only
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nexurejs-${{ matrix.os }}-node${{ matrix.node-version }}
        path: packages/

    - name: Create GitHub Release
      if: matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*

    - name: Publish to NPM
      if: matrix.os == 'ubuntu-latest'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_OPTIONS: "--max-old-space-size=4096"
